package lk.sunrise.clinic.service;

import lk.sunrise.clinic.dto.Dtos;
import lk.sunrise.clinic.exception.ClinicExceptions.NotFoundException;
import lk.sunrise.clinic.exception.ClinicExceptions.SlotUnavailableException;
import lk.sunrise.clinic.exception.ClinicExceptions.ValidationException;
import lk.sunrise.clinic.support.InMemoryClinicRepository;
import lk.sunrise.clinic.support.RecordingObserver;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.temporal.TemporalAdjusters;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Service-layer tests for AppointmentService.
 *
 * Requirements under test : FR-07, FR-09 to FR-16, NFR-04, NFR-05
 * Isolation               : InMemoryClinicRepository replaces MySQL entirely.
 *                           No database, no JDBC driver, no Spring context -
 *                           so a failure here can only be a fault in the
 *                           business logic.
 *
 * TEST DATA IS DERIVED, NOT INVENTED
 * ----------------------------------
 * Equivalence partitioning on the booking request:
 *      valid | missing field | unknown reference | closed day | outside hours |
 *      off-grain start | clashing slot
 * Boundary value analysis on opening hours (08:00-20:00) and on the 10-minute
 * turnaround buffer, since the defects the clinic reported are all at the
 * edges of those ranges, never in the middle.
 *
 * Dates are computed relative to today (the next Monday), so the suite cannot
 * start failing in a month's time because a hard-coded date drifted into the
 * past - AppointmentService rejects past dates by design.
 */
@DisplayName("AppointmentService - booking rules (FR-09..FR-16)")
class AppointmentServiceTest {

    private static final long DR_PERERA = 1L;
    private static final String PATIENT = "PAT-2026-000001";

    /** Always in the future, never the closed day (Sunday). */
    private static final LocalDate NEXT_MONDAY =
            LocalDate.now().with(TemporalAdjusters.next(DayOfWeek.MONDAY));

    private InMemoryClinicRepository repository;
    private RecordingObserver observer;
    private AppointmentService service;

    @BeforeEach
    void setUp() {
        repository = InMemoryClinicRepository.withClinicDefaults()
                .withPatient(PATIENT, "Nimal Silva")
                .withDentist(DR_PERERA, "Dr. Perera")
                .withTreatment("SCA", 1L, 30, "3500.00")     // 30-minute treatment
                .withTreatment("RCT", 2L, 90, "25000.00");   // 90-minute treatment

        observer = new RecordingObserver();
        service = new AppointmentService(repository, List.of(observer));
    }

    private Dtos.BookingRequest request(String treatment, LocalDate date, String start) {
        return new Dtos.BookingRequest(PATIENT, DR_PERERA, treatment, date,
                LocalTime.parse(start), "Routine visit");
    }

    // =================================================================
    @Nested
    @DisplayName("A valid request is booked (FR-09)")
    class HappyPath {

        @Test
        @DisplayName("returns an appointment number and stores the appointment")
        void booksSuccessfully() {
            Dtos.AppointmentDTO saved = service.book(request("SCA", NEXT_MONDAY, "10:00"), 1L);

            assertNotNull(saved, "a booked appointment must be returned");
            assertTrue(saved.appointmentNo().startsWith("APT-"),
                    "FR-08: the number is generated by the database, format APT-YYYY-NNNNNN");
            assertEquals("BOOKED", saved.status());
        }

        @Test
        @DisplayName("end time is start plus the treatment's own duration (FR-09)")
        void derivesEndTimeFromTreatmentDuration() {
            Dtos.AppointmentDTO scaling = service.book(request("SCA", NEXT_MONDAY, "08:00"), 1L);
            assertEquals(LocalTime.of(8, 30), scaling.endTime(),
                    "scaling takes 30 minutes");

            Dtos.AppointmentDTO rootCanal = service.book(request("RCT", NEXT_MONDAY, "14:00"), 1L);
            assertEquals(LocalTime.of(15, 30), rootCanal.endTime(),
                    "a root canal takes 90 minutes");
        }

        @Test
        @DisplayName("every registered observer is notified, and the service knows none of them")
        void publishesToObservers() {
            service.book(request("SCA", NEXT_MONDAY, "10:00"), 1L);

            assertEquals(1, observer.created.size(),
                    "the Observer pattern must fire exactly once per booking");
            assertTrue(observer.created.get(0).contains("Nimal Silva"));
        }

        @Test
        @DisplayName("booking still succeeds when no observer is registered")
        void worksWithNoObservers() {
            AppointmentService bare = new AppointmentService(repository, List.of());
            Dtos.AppointmentDTO saved = bare.book(request("SCA", NEXT_MONDAY, "11:00"), 1L);
            assertNotNull(saved, "observers are optional; booking must not depend on them");
        }
    }

    // =================================================================
    @Nested
    @DisplayName("Invalid input is rejected before anything is written (NFR-04)")
    class Validation {

        @Test
        void rejectsMissingPatient() {
            Dtos.BookingRequest req = new Dtos.BookingRequest(
                    "  ", DR_PERERA, "SCA", NEXT_MONDAY, LocalTime.of(10, 0), null);
            assertThrows(ValidationException.class, () -> service.book(req, 1L));
        }

        @Test
        void rejectsMissingDentist() {
            Dtos.BookingRequest req = new Dtos.BookingRequest(
                    PATIENT, null, "SCA", NEXT_MONDAY, LocalTime.of(10, 0), null);
            assertThrows(ValidationException.class, () -> service.book(req, 1L));
        }

        @Test
        void rejectsMissingTreatment() {
            Dtos.BookingRequest req = new Dtos.BookingRequest(
                    PATIENT, DR_PERERA, null, NEXT_MONDAY, LocalTime.of(10, 0), null);
            assertThrows(ValidationException.class, () -> service.book(req, 1L));
        }

        @Test
        void rejectsMissingDateOrTime() {
            Dtos.BookingRequest noDate = new Dtos.BookingRequest(
                    PATIENT, DR_PERERA, "SCA", null, LocalTime.of(10, 0), null);
            assertThrows(ValidationException.class, () -> service.book(noDate, 1L));

            Dtos.BookingRequest noTime = new Dtos.BookingRequest(
                    PATIENT, DR_PERERA, "SCA", NEXT_MONDAY, null, null);
            assertThrows(ValidationException.class, () -> service.book(noTime, 1L));
        }

        @Test
        @DisplayName("an unknown patient number is a 404, not a validation error (FR-07)")
        void rejectsUnknownPatient() {
            Dtos.BookingRequest req = new Dtos.BookingRequest(
                    "PAT-2026-999999", DR_PERERA, "SCA", NEXT_MONDAY, LocalTime.of(10, 0), null);
            assertThrows(NotFoundException.class, () -> service.book(req, 1L));
        }

        @Test
        void rejectsUnknownTreatmentCode() {
            assertThrows(NotFoundException.class,
                    () -> service.book(request("ZZZ", NEXT_MONDAY, "10:00"), 1L));
        }
    }

    // =================================================================
    @Nested
    @DisplayName("Opening hours - boundary value analysis (FR-12)")
    class OpeningHours {

        @Test
        @DisplayName("08:00 is the first bookable slot; 07:45 is not")
        void openingBoundary() {
            assertNotNull(service.book(request("SCA", NEXT_MONDAY, "08:00"), 1L),
                    "08:00 is ON the boundary and must be accepted");
            assertThrows(ValidationException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "07:45"), 1L),
                    "07:45 is one slot BELOW the boundary and must be refused");
        }

        @Test
        @DisplayName("a 30-minute treatment may start at 19:30 but not at 19:45")
        void closingBoundary() {
            assertNotNull(service.book(request("SCA", NEXT_MONDAY, "19:30"), 1L),
                    "19:30 + 30 minutes ends exactly at closing time");
            assertThrows(ValidationException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "19:45"), 1L),
                    "19:45 + 30 minutes would run past 20:00");
        }

        @Test
        @DisplayName("the clinic is closed on Sunday")
        void rejectsClosedDay() {
            LocalDate sunday = LocalDate.now().with(TemporalAdjusters.next(DayOfWeek.SUNDAY));
            ValidationException ex = assertThrows(ValidationException.class,
                    () -> service.book(request("SCA", sunday, "10:00"), 1L));
            assertTrue(ex.getMessage().toLowerCase().contains("closed"),
                    "the message must tell the receptionist why, not just refuse");
        }

        @Test
        @DisplayName("appointments cannot be booked in the past")
        void rejectsPastDate() {
            assertThrows(ValidationException.class,
                    () -> service.book(request("SCA", LocalDate.now().minusDays(1), "10:00"), 1L));
        }

        @ParameterizedTest(name = "start {0} is {1}")
        @CsvSource({
                "08:00, accepted",
                "08:15, accepted",
                "08:30, accepted",
                "08:45, accepted",
                "08:05, refused",
                "08:10, refused",
                "08:20, refused"
        })
        @DisplayName("starts fall on the 15-minute grain")
        void enforcesSlotGranularity(String start, String expected) {
            Runnable book = () -> service.book(request("SCA", NEXT_MONDAY, start), 1L);
            if ("accepted".equals(expected)) {
                book.run();
            } else {
                assertThrows(ValidationException.class, book::run);
            }
        }
    }

    // =================================================================
    @Nested
    @DisplayName("Double booking - the clinic's core rule (FR-10, FR-11, NFR-05)")
    class ClashDetection {

        @BeforeEach
        void bookTenToEleven() {
            // Dr. Perera is already busy 10:00-11:30 on the Monday.
            repository.withExistingBooking(DR_PERERA, NEXT_MONDAY, "10:00", "11:30");
        }

        @Test
        @DisplayName("an overlapping request is refused")
        void refusesOverlap() {
            assertThrows(SlotUnavailableException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "10:30"), 1L));
        }

        @Test
        @DisplayName("the refusal carries alternative slots rather than a bare error (FR-11)")
        void offersAlternatives() {
            SlotUnavailableException ex = assertThrows(SlotUnavailableException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "10:30"), 1L));

            List<LocalTime> slots = ex.getSuggestions();
            assertNotNull(slots, "the exception must carry suggestions");
            assertFalse(slots.isEmpty(), "the day is nearly empty, so slots exist");
            assertTrue(slots.size() <= 3, "at most three alternatives are offered");
            for (LocalTime slot : slots) {
                assertFalse(slot.isAfter(LocalTime.of(9, 30)) && slot.isBefore(LocalTime.of(11, 40)),
                        slot + " was offered but falls inside the busy period plus buffer");
            }
        }

        @Test
        @DisplayName("09:30 is refused, 09:15 is accepted - the buffer boundary")
        void bufferBeforeExistingAppointment() {
            // Existing appointment 10:00-11:30, turnaround buffer 10 minutes.
            // A 30-minute treatment at 09:30 ends at 10:00; widened by the buffer
            // it runs to 10:10, which intersects the existing start. One slot
            // earlier, 09:15-09:45 widens to 09:55 and clears it. These two are
            // adjacent slots either side of the boundary, which is where the
            // clinic's real double bookings happened.
            assertThrows(SlotUnavailableException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "09:30"), 1L),
                    "09:30-10:00 plus buffer runs into the existing appointment");

            assertNotNull(service.book(request("SCA", NEXT_MONDAY, "09:15"), 1L),
                    "09:15-09:45 plus buffer stops at 09:55 and clears 10:00");
        }

        @Test
        @DisplayName("11:45 is accepted - after the existing end plus buffer")
        void bufferAfterExistingAppointment() {
            assertNotNull(service.book(request("SCA", NEXT_MONDAY, "11:45"), 1L),
                    "11:45 is past 11:30 + 10 minutes turnaround");
        }

        @Test
        @DisplayName("a different dentist on the same day and time is fine")
        void differentDentistDoesNotClash() {
            repository.withDentist(2L, "Dr. Fernando");
            Dtos.BookingRequest other = new Dtos.BookingRequest(
                    PATIENT, 2L, "SCA", NEXT_MONDAY, LocalTime.of(10, 30), null);
            assertNotNull(service.book(other, 1L),
                    "the rule is per dentist, not per clinic");
        }

        @Test
        @DisplayName("the same dentist on a different day is fine")
        void differentDayDoesNotClash() {
            assertNotNull(service.book(request("SCA", NEXT_MONDAY.plusDays(1), "10:30"), 1L));
        }

        @Test
        @DisplayName("booking the same slot twice in a row is refused the second time")
        void secondIdenticalBookingIsRefused() {
            service.book(request("SCA", NEXT_MONDAY, "14:00"), 1L);
            assertThrows(SlotUnavailableException.class,
                    () -> service.book(request("SCA", NEXT_MONDAY, "14:00"), 1L),
                    "the first booking must occupy the slot");
        }
    }

    // =================================================================
    @Nested
    @DisplayName("Status changes (FR-13, FR-14, FR-15, FR-16)")
    class StatusTransitions {

        private String appointmentNo;

        @BeforeEach
        void bookOne() {
            appointmentNo = service.book(request("SCA", NEXT_MONDAY, "10:00"), 1L).appointmentNo();
        }

        @Test
        @DisplayName("a booked appointment can be cancelled with a reason")
        void cancelsWithReason() {
            service.cancel(appointmentNo, "Patient rang to postpone");
            assertEquals("CANCELLED", service.findByNumber(appointmentNo).status());
            assertEquals(1, observer.cancelled.size(),
                    "cancellation is published to observers too");
        }

        @Test
        @DisplayName("a cancellation without a reason is refused - the audit trail needs it")
        void refusesCancellationWithoutReason() {
            assertThrows(ValidationException.class, () -> service.cancel(appointmentNo, "  "));
            assertEquals("BOOKED", service.findByNumber(appointmentNo).status(),
                    "a refused cancellation must leave the appointment untouched");
        }

        @Test
        @DisplayName("an appointment cannot be cancelled twice")
        void refusesDoubleCancellation() {
            service.cancel(appointmentNo, "Patient rang");
            assertThrows(ValidationException.class,
                    () -> service.cancel(appointmentNo, "Rang again"));
        }

        @Test
        @DisplayName("only a booked appointment can be marked completed")
        void refusesCompletingACancelledAppointment() {
            service.cancel(appointmentNo, "Patient rang");
            assertThrows(ValidationException.class, () -> service.markCompleted(appointmentNo));
        }

        @Test
        @DisplayName("completing a booked appointment succeeds - the precondition for billing")
        void completesBookedAppointment() {
            service.markCompleted(appointmentNo);
            assertEquals("COMPLETED", service.findByNumber(appointmentNo).status());
        }

        @Test
        @DisplayName("an unknown appointment number is a 404 (FR-13)")
        void unknownAppointmentNumberIsNotFound() {
            assertThrows(NotFoundException.class, () -> service.findByNumber("APT-2026-999999"));
        }
    }
}
